### ISSUE TITLE
remove --component-button-size-height, as it is redundant

### ISSUE THREAD

**Issue by haakemon** [Altinn/figma-design-tokens#6]
### Description of the bug

Looks like the value for `--component-button-size-height` and `--component-toggle-size-height` is incorrect. It currently has the value of `3.6rem`, which is about 57.6px. From the designs, it looks like it should instead be 2.25rem, which is about 36px.

### Steps To Reproduce

Check value of `--component-button-size-height` and `--component-toggle-size-height`

**Comment by mrosvik** [comment]
@haakemon Do we need the height-value? The padding top and bottom will probably give it the correct height? Same for the min-width..? https://github.com/Altinn/figma-design-tokens/commit/3b8a9a8d24337b1e3ced1c8eeeea4b4d01321d69

**Comment by haakemon** [comment]
I'm fine with removing them 😁 Less stuff to maintain is always good

**Comment by mrosvik** [comment]
Done in https://github.com/Altinn/figma-design-tokens/commit/3b8a9a8d24337b1e3ced1c8eeeea4b4d01321d69

**Comment by mrosvik** [comment]
(You probably have to remove it on your side as well)

**Comment by haakemon** [comment]
Fixed in latest version of https://github.com/Altinn/altinn-design-system
